name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: asic_validation
          environment-file: environment2.yml
          auto-activate-base: false
      - run: |
          conda info
          conda list
